export const airportOptions = [
  ["DEL", "Delhi", "Indira Gandhi International Airport"],
  ["BOM", "Mumbai", "Chhatrapati Shivaji Maharaj International Airport"],
  ["BLR", "Bengaluru", "Kempegowda International Airport"],
  ["MAA", "Chennai", "Chennai International Airport"],
  ["CCU", "Kolkata", "Netaji Subhas Chandra Bose International Airport"],
  ["HYD", "Hyderabad", "Rajiv Gandhi International Airport"],
  ["COK", "Kochi", "Cochin International Airport"],
  ["GOI", "Goa", "Dabolim Airport"],
  ["GOX", "Goa", "Manohar International Airport"],
  ["PNQ", "Pune", "Pune Airport"],
  ["AMD", "Ahmedabad", "Sardar Vallabhbhai Patel International Airport"],
  ["JAI", "Jaipur", "Jaipur International Airport"],
  ["LKO", "Lucknow", "Chaudhary Charan Singh International Airport"],
  ["GAU", "Guwahati", "Lokpriya Gopinath Bordoloi International Airport"],
  ["IXC", "Chandigarh", "Chandigarh International Airport"],
  ["SXR", "Srinagar", "Srinagar International Airport"],
  ["PAT", "Patna", "Jay Prakash Narayan Airport"],
  ["BBI", "Bhubaneswar", "Biju Patnaik International Airport"],
  ["IXB", "Bagdogra", "Bagdogra Airport"],
  ["TRV", "Thiruvananthapuram", "Trivandrum International Airport"],
  ["VNS", "Varanasi", "Lal Bahadur Shastri International Airport"],
  ["IXR", "Ranchi", "Birsa Munda Airport"],
  ["IDR", "Indore", "Devi Ahilya Bai Holkar Airport"],
  ["NAG", "Nagpur", "Dr. Babasaheb Ambedkar International Airport"],
  ["DED", "Dehradun", "Jolly Grant Airport"],
  ["UDR", "Udaipur", "Maharana Pratap Airport"],
  ["IXZ", "Port Blair", "Veer Savarkar International Airport"],
  ["DXB", "Dubai", "Dubai International Airport"],
  ["AUH", "Abu Dhabi", "Zayed International Airport"],
  ["SIN", "Singapore", "Singapore Changi Airport"],
  ["BKK", "Bangkok", "Suvarnabhumi Airport"],
  ["HKT", "Phuket", "Phuket International Airport"],
  ["KUL", "Kuala Lumpur", "Kuala Lumpur International Airport"],
  ["MLE", "Malé", "Velana International Airport"],
  ["CMB", "Colombo", "Bandaranaike International Airport"],
  ["KTM", "Kathmandu", "Tribhuvan International Airport"],
  ["DOH", "Doha", "Hamad International Airport"],
  ["DPS", "Bali", "I Gusti Ngurah Rai International Airport"],
  ["MRU", "Mauritius", "Sir Seewoosagur Ramgoolam International Airport"],
  ["LHR", "London", "Heathrow Airport"],
  ["CDG", "Paris", "Charles de Gaulle Airport"],
  ["FCO", "Rome", "Leonardo da Vinci–Fiumicino Airport"],
  ["ZRH", "Zurich", "Zurich Airport"],
  ["JFK", "New York", "John F. Kennedy International Airport"],
  ["YYZ", "Toronto", "Toronto Pearson International Airport"],
  ["SYD", "Sydney", "Sydney Airport"],
] as const;
