export const searchTypes=["hotels","flights","trains","buses","taxis"]as const;export type SearchType=(typeof searchTypes)[number];
export type SearchItem={id:string;name:string;subtitle:string;image:string;gallery:string[];rating:number;reviews:number;basePrice:number;taxes:number;fees:number;features:string[];description:string;policy:string};
const hotelImages=["https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1400"];
const flightImages=["https://images.pexels.com/photos/358319/pexels-photo-358319.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/46148/aircraft-jet-landing-cloud-46148.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/912050/pexels-photo-912050.jpeg?auto=compress&cs=tinysrgb&w=1400"];
const trainImages=["https://images.pexels.com/photos/2031758/pexels-photo-2031758.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/302428/pexels-photo-302428.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/730134/pexels-photo-730134.jpeg?auto=compress&cs=tinysrgb&w=1400"];
const busImages=["https://images.pexels.com/photos/1178448/pexels-photo-1178448.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/3608967/pexels-photo-3608967.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=1400"];
const taxiImages=["https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1400","https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg?auto=compress&cs=tinysrgb&w=1400"];
const make=(id:string,name:string,subtitle:string,images:string[],rating:number,basePrice:number,taxes:number,fees:number,features:string[],description:string):SearchItem=>({id,name,subtitle,image:images[Number(id)-1],gallery:[images[Number(id)-1],...images.filter(x=>x!==images[Number(id)-1])],rating,reviews:128+Number(id)*43,basePrice,taxes,fees,features,description,policy:"Free cancellation is available on selected fares or rooms. Final terms are shown before confirmation."});
export const searchData:Record<SearchType,SearchItem[]>={
hotels:[make("1","The Grand Horizon","Luxury stay near the city centre",hotelImages,4.8,6200,1116,299,["Breakfast included","Free Wi-Fi","Pool & fitness","24x7 front desk"],"A refined stay with spacious rooms, thoughtful service and convenient access to major business and leisure districts."),make("2","Azure Bay Resort","Premium resort with pool and gardens",hotelImages,4.6,4800,864,249,["Breakfast included","Swimming pool","Airport transfer","Family rooms"],"A relaxed resort experience designed for families and leisure travellers, with landscaped spaces and modern comforts."),make("3","The Residency Suites","Comfortable serviced accommodation",hotelImages,4.5,3900,702,199,["Kitchenette","Free Wi-Fi","Work desk","Daily housekeeping"],"Well-equipped suites for official travel, extended stays and guests who value space, privacy and convenience.")],
flights:[make("1","BH Air Connect 401","Non-stop economy fare",flightImages,4.7,5450,981,349,["15 kg check-in","7 kg cabin bag","Non-stop","Standard seat"],"A convenient non-stop flight option with standard baggage and dependable timings."),make("2","Skyline Airways 218","Flexible economy fare",flightImages,4.5,6380,1148,299,["20 kg check-in","Meal included","Date change","Priority support"],"A flexible fare suited to official and business travel with additional baggage and included meal."),make("3","National Wings 709","Value economy fare",flightImages,4.4,4920,886,329,["15 kg check-in","7 kg cabin bag","One stop","Web check-in"],"A value-focused flight option balancing price, schedule and essential baggage.")],
trains:[make("1","Premium Express","AC Chair Car",trainImages,4.7,1280,64,39,["Air conditioned","Meal option","Reserved seat","Charging point"],"A fast daytime rail option with comfortable reserved seating and convenient onboard facilities."),make("2","Capital Superfast","AC 2 Tier",trainImages,4.6,2450,123,59,["Sleeping berth","Bedding included","Charging point","Pantry service"],"Comfortable overnight rail travel with reserved berths and essential onboard services."),make("3","Intercity Connect","AC 3 Tier",trainImages,4.4,1720,86,49,["Sleeping berth","Air conditioned","Reserved coach","Onboard catering"],"A dependable intercity option offering good value and comfortable reserved travel.")],
buses:[make("1","BlueLine Volvo","AC sleeper",busImages,4.6,1150,58,49,["Sleeper berth","Live tracking","Charging point","Water bottle"],"A comfortable overnight coach with individual sleeper berths and live journey tracking."),make("2","CityLink Premium","AC seater",busImages,4.4,820,41,39,["Recliner seat","Air conditioned","USB charging","GPS tracking"],"A clean and reliable premium coach for convenient intercity travel."),make("3","Royal Roadways","Volvo multi-axle",busImages,4.5,980,49,45,["Wide seats","Blanket","Charging point","Rest stop"],"A smooth long-distance coach experience with spacious seating and passenger comforts.")],
taxis:[make("1","Executive Sedan","Up to 4 passengers",taxiImages,4.8,1850,333,149,["AC sedan","Verified driver","Included kilometres","24x7 support"],"A comfortable sedan for airport transfers, local movement and official city travel."),make("2","Premium SUV","Up to 6 passengers",taxiImages,4.7,2850,513,199,["Spacious SUV","Verified driver","Extra luggage","24x7 support"],"A spacious vehicle ideal for families, teams and travellers carrying additional luggage."),make("3","City Hatchback","Up to 4 passengers",taxiImages,4.5,1250,225,99,["AC hatchback","Verified driver","Economical","Live tracking"],"An economical and dependable option for shorter transfers and travel within the city.")]};
export function getSearchItem(type:string,id:string){if(!searchTypes.includes(type as SearchType))return;return searchData[type as SearchType].find(item=>item.id===id)}export const formatPrice=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value);