"use client";
import {Suspense,useState} from "react";
import {ArrowLeft,ArrowRight,CheckCircle2,Mail} from "lucide-react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import AuthVisualPanel from "@/components/AuthVisualPanel";
import OtpInputs from "@/components/OtpInputs";
import {authService} from "@/lib/api/auth";
import {getErrorMessage} from "@/lib/api/client";
import "../auth.css";
function Login(){const router=useRouter();const[email,setEmail]=useState(""),[otp,setOtp]=useState(["","","","","",""]),[request,setRequest]=useState(""),[step,setStep]=useState<"login"|"otp"|"done">("login"),[error,setError]=useState(""),[loading,setLoading]=useState(false);
async function send(e:React.FormEvent){e.preventDefault();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return setError("Please enter a valid email address.");setLoading(true);setError("");try{const r=await authService.sendOtp(email);if(!r.success)throw Error(r.message);setRequest(r.request_id||"");setStep("otp")}catch(x){setError(getErrorMessage(x))}finally{setLoading(false)}}
async function verify(e:React.FormEvent){e.preventDefault();const code=otp.join("");if(!/^\d{6}$/.test(code))return setError("Enter the complete 6-digit code.");setLoading(true);try{const r=await authService.verifyOtp(email,request,code);if(!r.success)throw Error(r.message);if(r.access)localStorage.setItem("access_token",r.access);localStorage.setItem("bhli-auth",JSON.stringify({email}));window.dispatchEvent(new Event("storage"));setStep("done");setTimeout(()=>router.push("/"),900)}catch(x){setError(getErrorMessage(x))}finally{setLoading(false)}}
return <div className="auth-screen auth-login-theme"><div className="auth-frame"><section className="auth-form-panel"><div className="auth-top"><Link href="/" className="auth-back"><ArrowLeft size={17}/></Link><span>Not a member? <Link href="/register" className="auth-link">Sign up</Link></span></div><div className="auth-content">{step==="done"?<div className="text-center"><CheckCircle2 size={58} color="#26bd82" className="mx-auto mb-6"/><h1>Welcome Back</h1><p className="auth-subtitle">Opening your profile…</p></div>:<><h1>{step==="otp"?"Verify Login":"Sign In"}</h1><p className="auth-subtitle">{step==="otp"?`Enter the code sent to ${email}`:"Enter your email to receive a secure login code"}</p>{error&&<div className="auth-alert">{error}</div>}{step==="login"?<form className="auth-form" onSubmit={send}><Field label="Email address"><Mail size={18}/><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@email.com"/></Field><div className="auth-options"><label><input type="checkbox"/>Remember me</label></div><button className="auth-primary" disabled={loading}>{loading?"Please wait…":"Sign In"}<span><ArrowRight size={16}/></span></button></form>:<form onSubmit={verify}><OtpInputs value={otp} onChange={setOtp} idPrefix="login-otp"/><button className="auth-primary" disabled={loading}>{loading?"Verifying…":"Verify & Continue"}<span><ArrowRight size={16}/></span></button><button type="button" onClick={()=>setStep("login")} className="mt-5 w-full text-xs text-slate-400">Change email</button></form>}</>}</div><div className="auth-footer">🇮🇳 &nbsp; ENG</div></section><AuthVisualPanel/></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="auth-field"><span className="auth-label">{label}</span><span className="auth-control">{children}</span></label>}
export default function Page(){return <Suspense fallback={<div className="auth-screen"/>}><Login/></Suspense>}
