"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Camera, Images } from "lucide-react";
import { useRef } from "react";
import type { GalleryAlbum, GalleryCategory } from "@/lib/api/cms";

export default function AboutGallerySlider({ categories, albums }: { categories: GalleryCategory[]; albums: GalleryAlbum[] }) {
  const track = useRef<HTMLDivElement>(null);
  const move = (direction: number) => track.current?.scrollBy({ left: direction * Math.min(440, window.innerWidth * 0.82), behavior: "smooth" });

  return <section className="overflow-hidden bg-[#061f3b] px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-6"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.24em] text-[#13a5d8]"><Camera className="size-4"/>Our gallery</p><h2 className="mt-4 max-w-3xl font-serif text-4xl md:text-5xl">Stories from our journeys, events and partnerships.</h2><p className="mt-4 max-w-2xl text-white/55">Choose a category to explore its albums and photographs.</p></div><div className="hidden gap-2 sm:flex"><button onClick={()=>move(-1)} aria-label="Previous gallery categories" className="grid size-11 place-items-center rounded-full border border-white/20 hover:bg-white hover:text-[#061f3b]"><ArrowLeft/></button><button onClick={()=>move(1)} aria-label="Next gallery categories" className="grid size-11 place-items-center rounded-full bg-[#13a5d8] text-[#061f3b] hover:bg-white"><ArrowRight/></button></div></div><div ref={track} className="mt-10 flex snap-x snap-mandatory gap-5 overflow-x-auto pb-5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{categories.map(category=>{const categoryAlbums=albums.filter(album=>album.category_slug===category.slug);const images=categoryAlbums.flatMap(album=>Array.isArray(album.images)?album.images:[]).filter(image=>image.is_active);const cover=images.find(image=>image.is_cover)||images[0];return <Link key={category.id} href={`/about-us/gallery/${encodeURIComponent(category.slug)}`} className="group min-w-[82%] snap-start overflow-hidden rounded-3xl border border-white/10 bg-white/5 sm:min-w-[360px] lg:min-w-[400px]"><div className="relative h-72 overflow-hidden">{cover?<img src={cover.image} alt={cover.alt_text||category.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>:<div className="grid h-full place-items-center bg-white/5"><Images className="size-14 text-white/20"/></div>}<div className="absolute inset-0 bg-gradient-to-t from-[#04172b] via-transparent to-transparent"/><span className="absolute bottom-5 left-5 rounded-full bg-[#13a5d8] px-3 py-1 text-xs font-bold text-[#061f3b]">{categoryAlbums.length} {categoryAlbums.length===1?"album":"albums"}</span></div><div className="p-6"><div className="flex items-center justify-between gap-4"><h3 className="font-serif text-3xl">{category.name}</h3><ArrowRight className="size-5 transition-transform group-hover:translate-x-1"/></div><p className="mt-3 text-sm text-white/50">View category details</p></div></Link>})}{categories.length===0&&<div className="w-full rounded-3xl border border-white/10 p-10 text-center text-white/50">Gallery categories will appear here when available.</div>}</div></div></section>;
}
