import Link from"next/link";import{ArrowRight,Bus,CalendarDays,Car,Coins,Ship,Hotel,Map,Plane,ShieldCheck,Ticket,Train,UtensilsCrossed}from"lucide-react";
const items=[
  ["Hotel reservations","Verified stays for business, duty and leisure.",Hotel,"/services/hotel-reservations","https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Flight bookings","Domestic and international ticketing support.",Plane,"/services/flight-bookings","https://images.pexels.com/photos/358319/pexels-photo-358319.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Train tickets","Rail reservations with itinerary coordination.",Train,"/services/train-ticket-booking","https://images.pexels.com/photos/2031758/pexels-photo-2031758.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Bus tickets","Reliable intercity and group transport options.",Bus,"/services/bus-ticket-booking","https://images.pexels.com/photos/1178448/pexels-photo-1178448.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Taxi services","Airport transfers, local travel and outstation cabs.",Car,"/services/taxi-services","https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Holiday packages","Curated family, group and individual escapes.",Map,"/services/holiday-packages","https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Cruise holidays","Selected sailings and end-to-end cruise planning.",Ship,"/services/cruise-holidays","https://images.pexels.com/photos/144237/pexels-photo-144237.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Visa assistance","Document guidance and application coordination.",Ticket,"/services/visa-assistance","https://images.pexels.com/photos/7235894/pexels-photo-7235894.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Travel insurance","Protection options suited to your journey.",ShieldCheck,"/services/travel-insurance","https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Currency exchange","Convenient foreign exchange assistance.",Coins,"/services/currency-exchange","https://images.pexels.com/photos/4386366/pexels-photo-4386366.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Event management","Thoughtful corporate, social and official events.",CalendarDays,"/services/event-management","https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Catering services","Professional culinary and hospitality setup for all occasions.",UtensilsCrossed,"/services/catering-services","https://images.pexels.com/photos/3298647/pexels-photo-3298647.jpeg?auto=compress&cs=tinysrgb&w=900"],
  ["Travel consultancy","Policy-aware planning for institutions and teams.",ArrowRight,"/services/travel-consultancy","https://images.pexels.com/photos/3769138/pexels-photo-3769138.jpeg?auto=compress&cs=tinysrgb&w=900"]
];
export default function Services(){return <div className="bg-[#f5f9fc] text-[#122b42]"><section className="relative overflow-hidden bg-[#062b50] px-5 py-24 text-white lg:px-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(215,181,109,.18),transparent_35%)]"/><div className="relative mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#13a5d8]">Our services</p><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-tight md:text-7xl">One partner for every part of the journey.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/60">Travel, hospitality, mobility and event solutions delivered with clarity, care and dependable support.</p></div></section><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map(([t,d,I,h,img])=><Link href={String(h)} key={String(t)} className="group overflow-hidden rounded-3xl border border-black/10 bg-white"><div className="relative h-48 overflow-hidden"><img src={String(img)} alt={String(t)} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#061f3b]/50 to-transparent"/><span className="absolute bottom-4 left-5 grid size-12 place-items-center rounded-2xl bg-white/92 text-[#087fbe] shadow-lg backdrop-blur"><I className="size-6"/></span></div><div className="p-7"><div className="flex items-start justify-between gap-4"><h2 className="font-serif text-2xl transition-colors group-hover:text-[#087fbe]">{String(t)}</h2><ArrowRight className="size-5 shrink-0 text-black/25 transition group-hover:translate-x-1 group-hover:text-[#087fbe]"/></div><p className="mt-3 text-sm leading-7 text-black/55">{String(d)}</p></div></Link>)}</div></section><section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="grid overflow-hidden rounded-[2rem] bg-[#07345d] text-white lg:grid-cols-2"><img src="https://images.pexels.com/photos/3769138/pexels-photo-3769138.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Travel planning" className="h-full min-h-[360px] w-full object-cover"/><div className="p-8 md:p-14"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#13a5d8]">Need a tailored solution?</p><h2 className="mt-4 font-serif text-4xl">Tell us the outcome. We will plan the route.</h2><p className="mt-5 leading-8 text-white/60">For group movement, official travel, conferences or complex itineraries, our team can shape a solution around your requirements.</p><Link href="/contact-us" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#13a5d8] px-6 py-3 font-bold text-[#061f3b]">Start an enquiry <ArrowRight className="size-4"/></Link></div></div></section></div>}


