"use client";
import {useState} from "react";
import {ArrowLeft,ArrowRight,Check,CheckCircle2,Mail,Smartphone,UserRound} from "lucide-react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import AuthVisualPanel from "@/components/AuthVisualPanel";
import OtpInputs from "@/components/OtpInputs";
import "../auth.css";
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,MOBILE=/^[6-9]\d{9}$/;
export default function Register(){const router=useRouter();const[v,setV]=useState({firstName:"",lastName:"",email:"",mobile:"",serviceNum:"",rank:"",employeeId:"",department:""}),[otp,setOtp]=useState(["","","","","",""]),[step,setStep]=useState<"form"|"otp"|"done">("form"),[error,setError]=useState("");const update=(k:keyof typeof v,x:string)=>setV({...v,[k]:x});
function submit(e:React.FormEvent){e.preventDefault();if(v.firstName.trim().length<2||v.lastName.trim().length<2)return setError("First and last name must contain at least 2 characters.");if(!EMAIL.test(v.email))return setError("Please enter a valid email address.");if(!MOBILE.test(v.mobile))return setError("Enter a valid 10-digit Indian mobile number.");if(!v.rank.trim())return setError("Please enter the officer's rank.");if(v.employeeId && !/^\d{4}$/.test(v.employeeId))return setError("Employee ID must contain exactly the last 4 digits.");if(!v.department)return setError("Please select the defence sector or department.");setError("");setStep("otp")}
function finish(e:React.FormEvent){e.preventDefault();if(!/^\d{6}$/.test(otp.join("")))return setError("Enter the complete 6-digit code.");const p={name:`${v.firstName} ${v.lastName}`,...v,authenticatedAt:new Date().toISOString()};localStorage.setItem("bhli-auth",JSON.stringify({email:v.email,authenticatedAt:p.authenticatedAt}));localStorage.setItem("bhli-profile-details",JSON.stringify(p));window.dispatchEvent(new Event("storage"));setStep("done");setTimeout(()=>router.push("/profile"),900)}
return <div className="auth-screen auth-login-theme auth-register-screen"><div className="auth-frame"><section className="auth-form-panel"><div className="auth-top"><Link href="/" className="auth-back"><ArrowLeft size={17}/></Link><span>Already member? <Link href="/login" className="auth-link">Sign in</Link></span></div><div className="auth-content">{step==="done"?<div className="text-center"><CheckCircle2 size={58} color="#26bd82" className="mx-auto mb-6"/><h1>Account Created</h1><p className="auth-subtitle">Opening your profile…</p></div>:<><h1>{step==="otp"?"Verify Mobile":"Sign Up"}</h1><p className="auth-subtitle">{step==="otp"?`Enter the code sent to +91 ${v.mobile}`:"Secure your travel experience with Booking Hospitality"}</p>{error&&<div className="auth-alert">{error}</div>}{step==="form"?<form id="signup-form" className="auth-form" onSubmit={submit}><div className="auth-row"><Input label="First name" icon={<UserRound/>} value={v.firstName} change={x=>update("firstName",x)} placeholder="Daniel"/><Input label="Last name" icon={<UserRound/>} value={v.lastName} change={x=>update("lastName",x)} placeholder="Ahmadi"/></div><Input label="Email address" icon={<Mail/>} value={v.email} change={x=>update("email",x)} placeholder="daniel@gmail.com" valid={EMAIL.test(v.email)}/><Input label="Mobile number" icon={<Smartphone/>} value={v.mobile} change={x=>update("mobile",x.replace(/\D/g,"").slice(0,10))} placeholder="9876543210" valid={MOBILE.test(v.mobile)}/><Input label="Service number" hint="Optional" value={v.serviceNum} change={x=>update("serviceNum",x)} placeholder="e.g. IC-XXXXX"/><Input label="Officer's rank *" value={v.rank} change={x=>update("rank",x)} placeholder="Rank / designation"/><Input label="Employee ID - last 4 digits" hint="Optional" value={v.employeeId} change={x=>update("employeeId",x.replace(/\D/g,"").slice(0,4))} placeholder="Last 4 digits"/><label className="auth-field"><span className="auth-label">Defence sector / department *</span><span className="auth-control"><select required value={v.department} onChange={e=>update("department",e.target.value)}><option value="">Select department</option>{["Air Force","Army","CISF","Coast Guard","DRDO","MOD","Navy","Paramilitary Forces","Other"].map(x=><option key={x} value={x}>{x}</option>)}</select></span></label></form>:<form onSubmit={finish}><OtpInputs value={otp} onChange={setOtp} idPrefix="register-otp"/><button className="auth-primary">Verify & Create Account<span><ArrowRight size={16}/></span></button><button type="button" onClick={()=>setStep("form")} className="mt-5 w-full text-xs text-slate-400">Back to details</button></form>}</>}</div>{step==="form"&&<button type="submit" form="signup-form" className="auth-primary auth-register-submit">Sign Up<span><ArrowRight size={16}/></span></button>}<div className="auth-footer">🇮🇳 &nbsp; ENG</div></section><AuthVisualPanel/></div></div>}
function Input({label,hint,icon,value,change,placeholder,valid}:{label:string;hint?:string;icon?:React.ReactNode;value:string;change:(x:string)=>void;placeholder:string;valid?:boolean}){const email=label==="Email address",mobile=label==="Mobile number",name=label.includes("name");return <label className="auth-field"><span className="auth-label">{label}{hint&&<small>{hint}</small>}</span><span className="auth-control">{icon&&<i>{icon}</i>}<input required={hint!=="Optional"} type={email?"email":mobile?"tel":"text"} minLength={name?2:undefined} pattern={mobile?"[6-9][0-9]{9}":undefined} maxLength={mobile?10:undefined} autoComplete={email?"email":mobile?"tel":"off"} value={value} onChange={e=>change(e.target.value)} placeholder={placeholder}/>{valid&&<Check size={17} color="#25bf82"/>}</span></label>}
